### ISSUE TITLE
Save Moment Maps to file

### ISSUE THREAD

**Issue by gtudisco** [VisIVOLab/ViaLacteaVisualAnalytics#127]
Currently moment maps are generated and visualized on-the-fly.
The user may also want to export them to file (in FITS format).

**Comment by milebene** [comment]
The header of the fits file of the moment map must be produced. The header must be a copy of the header of the cube with the following modification:
 1. New line(S) in the HISTORY must be added telling that is a moment # map
 2. keyword NAXIS must be change to '2'
 3. all the keywords related to the third axis must be deleted
 4. BTYPE and BUNIT must be changed depending on the order of the moment, in particular
     Moment 0 – the integrated value of the spectrum BUNIT will be BUNIT of the original cube * CUNIT3 of the original cube
     Moment 1 – the intensity weighted coordinate. BUNIT will be CUNIT3 of the cube
     Moment 2 -  the intensity weighted dispersion of the coordinate . BUNIT will be CUNIT3 of the original  cube
     Moment 6 – the root mean square of the spectrum. BUNIT will be the same BUNIT of the original cube
     Moment 8 - the maximum value of the spectrum. BUNIT will be the same BUNIT of the original cube
     Moment 10 – the minimum value of the spectrum. BUNIT will be the same BUNIT of the original cube

**Comment by milebene** [comment]
Giuseppe, you should add the moment 2 as the possible moment to be produced
