### ISSUE TITLE
Create PV Plot

### ISSUE THREAD

**Issue by fvitello** [VisIVOLab/ViaLacteaVisualAnalytics#18]
Investigate if is possible to implement directly the pv plot generation or if it is more convenient to integrate external library such as https://learn.astropy.org/tutorials/PVDiagramPlotting.html

**Comment by fvitello** [comment]
@gtudisco is this implemented? Can we use the python lib ?

**Comment by gtudisco** [comment]
Not yet. I had started with a C++ implementation, but now with pybind11 we can use the Python library instead. Will probably do after #102.

**Comment by milebene** [comment]
AI Giuseppe modificare la finestra di visualizzazione del PV plot lasciando solo le opzioni di gestione della figura e correggendo l’asse x
AI Giuseppe  va aggiunto un modo per capire il punto di origine e la direzione  dell’offset lungo il segmento definito sulla moment map, dinamico o statico. Alcune possibilità discusse sono di disegnare una freccia invece che un segmento o scrivere le coordinate dell’offset sul segmento.
