### ISSUE TITLE
Interactive position-velocity slicing

### ISSUE THREAD

**Issue by fvitello** [VisIVOLab/ViaLacteaVisualAnalytics#42]
the tool should emulate [kpvslice](https://www.atnf.csiro.au/computing/software/karma/user-manual/kpvslice.html)

Allow the user to use a two-dimensional image to define a slice through a three-dimensional data cube.

A typical use is to examine the position-velocity diagram for a slice drawn along the major axis of a rotating galaxy. The slice is drawn on the total column density or velocity field map, and the corresponding position-velocity diagram will appear in the other window. The slice can be moved around interactively for quick comparison of different regions.

How the Slice is Computed

The slices are interpolated using a weighted average of the nearest four pixels. The weighting is inversely proportional to the distance of the point in the slice from the centre of the neighbour pixel.

So the ``thickness'' is basically one spatial pixel, but the width of the region that the interpolation is made over varies depending on the angle of the slice with respect to the pixel grid. It is least (3 pixels wide) when the slice is along the x or y axis of the pixel grid, and greatest (sqrt(2)*3) when the slice is at 45tex2html_wrap_inline4890 to the pixel grid.

The interpolation is made only with respect to the pixel grid, so the above numbers are only strictly true if the x and y directions have the same spatial scales. If the arcsec/pixel is different in the x and y directions, the width of the slice in arcsec will change from differently as the angle of the slice w.r.t the pixel grid changes.

         ++++.+++++++
         +++++.*+++++
         +++++*x*++++   'x' is the current pixel, '*' are the neighbours
         ++++++*.++++   '.' is the other pixels in the slice.
         ++++++++.+++
         +++++++++.++

**Comment by milebene** [comment]
This functionality has been implemented in the developed Position-Velocity tool (isue 18).
The issue can be closed

**Comment by fvitello** [comment]
closed by issue 18 https://github.com/VisIVOLab/ViaLacteaVisualAnalytics/issues/18
