### ISSUE TITLE
Read downsampled Cube

### ISSUE THREAD

**Issue by fvitello** [VisIVOLab/ViaLacteaVisualAnalytics#79]
Adapt reader according to what is already implemented in legacy application. 
Cube should be downsampled to fit the available memory (or a value defined in the settings), this operations must not change the "size" of the visualized cube. 
Selected slice should be loaded in memory not the entire cube.

**Comment by gtudisco** [comment]
Closed in d2a3676f7d1e193fd71d87a26efa275d7aa47763
